# Generated by Django 4.2.4 on 2023-08-03 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_video_remove_additionalimage_bb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Товар')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subrubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rubric',
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(default=7, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Объявление'),
            preserve_default=False,
        ),
    ]
